services:

  # console:

  # grafana:

  # logdb:

  # orchestrator:

  simulator:
    container_name: simulator
    build:
      context: ./simulator
      dockerfile: Dockerfile
    ports:
      - "8900:8900"
      - "8910:8910"
    tty: true
