services:

  simulator:
   container_name: simulator-${CAMPAIGN_ID}
   build:
    dockerfile: simulator/Dockerfile
   volumes:
     - s2e-log:/root/aobc-sils/s2e/logs/
   networks:
      control:
      campaign:

  simulation-logger:
    container_name: simulation-logger-${CAMPAIGN_ID}
    build:
      dockerfile: simulation-logger/Dockerfile
    volumes:
      - s2e-log:/s2e-log
    environment:
      - CAMPAIGN_ID=${CAMPAIGN_ID}
      - CAMPAIGN_START_TIMESTAMP_MS=${CAMPAIGN_START_TIMESTAMP_MS}
    networks:
      control:
      campaign:
    depends_on:
      - simulator

  tlmcmd-bridge:
    container_name: tlmcmd-bridge-${CAMPAIGN_ID}
    build:
      dockerfile: tlmcmd-bridge/Dockerfile
    volumes:
      - tmtc-cargo-target:/tmtc/target
    environment:
      - CAMPAIGN_ID=${CAMPAIGN_ID}
      - CAMPAIGN_START_TIMESTAMP_MS=${CAMPAIGN_START_TIMESTAMP_MS}
    networks:
      control:
      campaign:
    depends_on:
      - simulator

  kble:
    container_name: kble-${CAMPAIGN_ID}
    build:
      dockerfile: kble/Dockerfile
    environment:
      - CAMPAIGN_ID=${CAMPAIGN_ID}
    networks:
      campaign:
    depends_on:
      - tlmcmd-bridge
    
volumes:
  tmtc-cargo-target:
  s2e-log:
  app-upload: 

networks:
  control:
    external: true
  campaign:
