{
 "title": "New dashboard",
 "time": { "from": "2023-02-09T15:00:00.000Z", "to": "2023-02-10T14:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "Simulation ID",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurements(bucket: \"simulation\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Position",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_latitude[rad]\")\r\n  |> map(fn: (r) => ({r with _value: r._value * 180.0 / math.pi}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_longitude[rad]\")\r\n  |> map(fn: (r) => ({r with _value: r._value * 180.0 / math.pi}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_altitude[m]\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Velocity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_velocity_i_x[m/s]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_velocity_i_y[m/s]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_velocity_i_z[m/s]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_acceleration_i_x[m/s2]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_acceleration_i_y[m/s2]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_acceleration_i_z[m/s2]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Position",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_latitude[rad]\")\r\n  |> map(fn: (r) => ({r with _value: r._value * 180.0 / math.pi}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_longitude[rad]\")\r\n  |> map(fn: (r) => ({r with _value: r._value * 180.0 / math.pi}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_altitude[m]\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Velocity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_velocity_i_x[m/s]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_velocity_i_y[m/s]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_velocity_i_z[m/s]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_acceleration_i_x[m/s2]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_acceleration_i_y[m/s2]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    },
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"simulation\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${id}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"spacecraft_acceleration_i_z[m/s2]\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  }
 ]
}