apiVersion: 1

prune: true

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://log-db:8086
    basicAuth: false
    jsonData:
      version: Flux
      defaultBucket: simulation
      organization: satellite-cloud
      tlsSkipVerify: true
    secureJsonData:
      token: admin-token
